In [3]:
import pandas as pd

In [8]:
fl_restuarants2021 = 'CBP2021.CB2100CBP-2024-05-10T030649.csv'

df_fl2021= pd.read_csv(fl_restuarants2021)

df_fl2021

,Geographic Area Name (NAME),2017 NAICS code (NAICS2017),Meaning of NAICS Code (NAICS2017_LABEL),Meaning of Legal form of organization code (LFO_LABEL),Meaning of Employment size of establishments code (EMPSZES_LABEL),Year (YEAR),Number of establishments (ESTAB),"Annual payroll ($1,000) (PAYANN)","First-quarter payroll ($1,000) (PAYQTR1)",Number of employees (EMP)
0,Florida,722511,Full-service restaurants,All establishments,All establishments,2021,"17,442","10,425,750","2,253,243","384,600"
1,Florida,722511,Full-service restaurants,All establishments,Establishments with less than 5 employees,2021,"4,762","393,611","44,017","7,697"
2,Florida,722511,Full-service restaurants,All establishments,Establishments with 5 to 9 employees,2021,"2,673","450,637","99,869","18,005"
3,Florida,722511,Full-service restaurants,All establishments,Establishments with 10 to 19 employees,2021,"3,273","1,144,722","258,555","45,999"
4,Florida,722511,Full-service restaurants,All establishments,Establishments with 20 to 49 employees,2021,"4,587","3,654,301","812,985","145,091"
5,Florida,722511,Full-service restaurants,All establishments,Establishments with 50 to 99 employees,2021,"1,799","3,314,202","730,674","120,096"
6,Florida,722511,Full-service restaurants,All establishments,Establishments with 100 to 249 employees,2021,341,"1,341,968","286,545","45,035"
7,Florida,722511,Full-service restaurants,All establishments,Establishments with 250 to 499 employees,2021,5,"50,447","7,242","1,599"
8,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,All establishments,2021,"3,594","2,999,456","640,969","109,298"
9,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with less than 5 employees,2021,938,"65,886","8,745","1,511"
10,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with 5 to 9 employees,2021,401,"63,687","14,776","2,597"
11,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with 10 to 19 employees,2021,488,"166,295","39,040","6,978"
12,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with 20 to 49 employees,2021,904,"794,985","173,777","30,934"
13,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with 50 to 99 employees,2021,745,"1,374,194","301,044","49,948"
14,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with 100 to 249 employees,2021,114,"444,031","90,849","15,732"
15,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with 250 to 499 employees,2021,3,"29,192","2,077","1,022"
16,Florida,722511,Full-service restaurants,S-corporations,All establishments,2021,"8,997","4,470,676","987,319","167,174"
17,Florida,722511,Full-service restaurants,S-corporations,Establishments with less than 5 employees,2021,"2,382","184,514","25,902","4,409"
18,Florida,722511,Full-service restaurants,S-corporations,Establishments with 5 to 9 employees,2021,"1,628","281,486","63,258","11,057"
19,Florida,722511,Full-service restaurants,S-corporations,Establishments with 10 to 19 employees,2021,"2,020","726,226","164,354","28,213"
20,Florida,722511,Full-service restaurants,S-corporations,Establishments with 20 to 49 employees,2021,"2,274","1,789,229","403,277","69,491"
21,Florida,722511,Full-service restaurants,S-corporations,Establishments with 50 to 99 employees,2021,565,"1,003,627","223,345","37,175"
22,Florida,722511,Full-service restaurants,S-corporations,Establishments with 100 to 249 employees,2021,127,"469,807","103,224","16,502"
23,Florida,722511,Full-service restaurants,Individual proprietorships,All establishments,2021,"1,154","455,256","100,251","20,781"
24,Florida,722511,Full-service restaurants,Individual proprietorships,Establishments with less than 5 employees,2021,397,"22,506","2,615",570
25,Florida,722511,Full-service restaurants,Individual proprietorships,Establishments with 5 to 9 employees,2021,154,"20,141","4,574","1,027"
26,Florida,722511,Full-service restaurants,Individual proprietorships,Establishments with 10 to 19 employees,2021,185,"52,006","11,748","2,689"
27,Florida,722511,Full-service restaurants,Individual proprietorships,Establishments with 20 to 49 employees,2021,343,"218,438","50,506","10,974"
28,Florida,722511,Full-service restaurants,Individual proprietorships,Establishments with 50 to 99 employees,2021,64,"110,600","23,932","4,159"
29,Florida,722511,Full-service restaurants,Individual proprietorships,Establishments with 100 to 249 employees,2021,11,"31,565","6,876","1,362"
30,Florida,722511,Full-service restaurants,Partnerships,All establishments,2021,"3,673","2,492,426","523,083","87,063"
31,Florida,722511,Full-service restaurants,Partnerships,Establishments with less than 5 employees,2021,"1,037","118,723","6,677","1,198"
32,Florida,722511,Full-service restaurants,Partnerships,Establishments with 5 to 9 employees,2021,485,"84,709","17,048","3,289"
33,Florida,722511,Full-service restaurants,Partnerships,Establishments with 10 to 19 employees,2021,574,"198,337","43,029","8,029"
34,Florida,722511,Full-service restaurants,Partnerships,Establishments with 20 to 49 employees,2021,"1,062","848,577","184,832","33,599"
35,Florida,722511,Full-service restaurants,Partnerships,Establishments with 50 to 99 employees,2021,424,"825,371","182,000","28,757"
36,Florida,722511,Full-service restaurants,Partnerships,Establishments with 100 to 249 employees,2021,89,"396,565","85,596","11,439"
37,Florida,722511,Full-service restaurants,Non-profit,All establishments,2021,14,"3,876",465,96
38,Florida,722511,Full-service restaurants,Non-profit,Establishments with less than 5 employees,2021,7,"1,965",78,9
39,Florida,722511,Full-service restaurants,Non-profit,Establishments with 10 to 19 employees,2021,4,"1,022",207,55
40,Florida,722511,Full-service restaurants,Other noncorporate legal forms of organization,All establishments,2021,10,"4,060","1,156",188
41,Florida,722511,Full-service restaurants,Other noncorporate legal forms of organization,Establishments with 5 to 9 employees,2021,3,470,184,22
42,Florida,722511,Full-service restaurants,Other noncorporate legal forms of organization,Establishments with 20 to 49 employees,2021,3,"2,327",442,74

In [9]:
fl_restuarants2020 = 'CBP2020.CB2000CBP-2024-05-10T032217.csv'

df_fl2020= pd.read_csv(fl_restuarants2020)

df_fl2020

,Geographic Area Name (NAME),2017 NAICS code (NAICS2017),Meaning of NAICS code (NAICS2017_LABEL),Meaning of Legal form of organization code (LFO_LABEL),Meaning of Employment size of establishments code (EMPSZES_LABEL),Year (YEAR),Number of establishments (ESTAB),"Annual payroll ($1,000) (PAYANN)","First-quarter payroll ($1,000) (PAYQTR1)",Number of employees (EMP)
0,Florida,722511,Full-service restaurants,All establishments,All establishments,2020,"17,110","7,800,462","2,467,806","436,334"
1,Florida,722511,Full-service restaurants,All establishments,Establishments with less than 5 employees,2020,"4,426","289,737","40,249","7,374"
2,Florida,722511,Full-service restaurants,All establishments,Establishments with 5 to 9 employees,2020,"2,553","310,337","87,471","17,368"
3,Florida,722511,Full-service restaurants,All establishments,Establishments with 10 to 19 employees,2020,"3,053","776,319","226,769","42,936"
4,Florida,722511,Full-service restaurants,All establishments,Establishments with 20 to 49 employees,2020,"4,386","2,424,846","759,426","140,597"
5,Florida,722511,Full-service restaurants,All establishments,Establishments with 50 to 99 employees,2020,"2,074","2,441,407","814,524","138,999"
6,Florida,722511,Full-service restaurants,All establishments,Establishments with 100 to 249 employees,2020,591,"1,343,003","459,017","78,632"
7,Florida,722511,Full-service restaurants,All establishments,Establishments with 250 to 499 employees,2020,22,"144,154","57,020","7,263"
8,Florida,722511,Full-service restaurants,All establishments,Establishments with 500 to 999 employees,2020,5,"70,659","23,330","3,165"
9,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,All establishments,2020,"3,755","2,436,255","801,750","144,742"
10,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with less than 5 employees,2020,872,"52,396","9,446","1,443"
11,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with 5 to 9 employees,2020,398,"48,271","12,862","2,636"
12,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with 10 to 19 employees,2020,422,"108,885","31,029","6,008"
13,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with 20 to 49 employees,2020,946,"516,179","163,300","32,596"
14,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with 50 to 99 employees,2020,799,"965,628","320,182","54,456"
15,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with 100 to 249 employees,2020,299,"597,630","207,948","39,906"
16,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with 250 to 499 employees,2020,15,"84,966","36,371","5,119"
17,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with 500 to 999 employees,2020,4,"62,300","20,612","2,578"
18,Florida,722511,Full-service restaurants,S-corporations,All establishments,2020,"8,738","3,368,781","1,009,049","176,702"
19,Florida,722511,Full-service restaurants,S-corporations,Establishments with less than 5 employees,2020,"2,197","138,326","22,387","4,173"
20,Florida,722511,Full-service restaurants,S-corporations,Establishments with 5 to 9 employees,2020,"1,534","192,361","54,165","10,487"
21,Florida,722511,Full-service restaurants,S-corporations,Establishments with 10 to 19 employees,2020,"1,927","504,120","145,065","27,089"
22,Florida,722511,Full-service restaurants,S-corporations,Establishments with 20 to 49 employees,2020,"2,275","1,313,071","400,097","70,720"
23,Florida,722511,Full-service restaurants,S-corporations,Establishments with 50 to 99 employees,2020,647,"786,149","250,609","42,349"
24,Florida,722511,Full-service restaurants,S-corporations,Establishments with 100 to 249 employees,2020,154,"397,272","123,983","20,571"
25,Florida,722511,Full-service restaurants,S-corporations,Establishments with 250 to 499 employees,2020,4,"37,482","12,743","1,313"
26,Florida,722511,Full-service restaurants,Individual proprietorships,All establishments,2020,"1,029","337,493","110,425","21,102"
27,Florida,722511,Full-service restaurants,Individual proprietorships,Establishments with less than 5 employees,2020,411,"20,120","2,474",600
28,Florida,722511,Full-service restaurants,Individual proprietorships,Establishments with 5 to 9 employees,2020,144,"13,399","4,139",972
29,Florida,722511,Full-service restaurants,Individual proprietorships,Establishments with 10 to 19 employees,2020,158,"35,232","10,146","2,204"
30,Florida,722511,Full-service restaurants,Individual proprietorships,Establishments with 20 to 49 employees,2020,149,"74,996","24,108","4,822"
31,Florida,722511,Full-service restaurants,Individual proprietorships,Establishments with 50 to 99 employees,2020,154,"142,844","51,262","10,467"
32,Florida,722511,Full-service restaurants,Individual proprietorships,Establishments with 100 to 249 employees,2020,12,"37,799","14,477","1,712"
33,Florida,722511,Full-service restaurants,Partnerships,All establishments,2020,"3,564","1,650,281","544,036","93,336"
34,Florida,722511,Full-service restaurants,Partnerships,Establishments with less than 5 employees,2020,937,"78,414","5,831","1,146"
35,Florida,722511,Full-service restaurants,Partnerships,Establishments with 5 to 9 employees,2020,475,"56,199","16,240","3,256"
36,Florida,722511,Full-service restaurants,Partnerships,Establishments with 10 to 19 employees,2020,542,"127,394","40,270","7,568"
37,Florida,722511,Full-service restaurants,Partnerships,Establishments with 20 to 49 employees,2020,"1,010","517,333","171,057","32,288"
38,Florida,722511,Full-service restaurants,Partnerships,Establishments with 50 to 99 employees,2020,471,"543,677","191,224","31,542"
39,Florida,722511,Full-service restaurants,Partnerships,Establishments with 100 to 249 employees,2020,126,"310,302","112,609","16,443"
40,Florida,722511,Full-service restaurants,Non-profit,All establishments,2020,16,"2,364",678,155
41,Florida,722511,Full-service restaurants,Non-profit,Establishments with less than 5 employees,2020,8,451,111,12
42,Florida,722511,Full-service restaurants,Non-profit,Establishments with 10 to 19 employees,2020,3,416,148,47
43,Florida,722511,Full-service restaurants,Non-profit,Establishments with 20 to 49 employees,2020,3,"1,390",354,79
44,Florida,722511,Full-service restaurants,Other noncorporate legal forms of organization,All establishments,2020,8,"5,288","1,868",297
45,Florida,722511,Full-service restaurants,Other noncorporate legal forms of organization,Establishments with 20 to 49 employees,2020,3,"1,877",510,92
46,Florida,722511,Full-service restaurants,Other noncorporate legal forms of organization,Establishments with 50 to 99 employees,2020,3,"3,109","1,247",185

In [11]:
fl_restuarants2019 = 'CBP2019.CB1900CBP-2024-05-10T032249.csv'

df_fl2019 = pd.read_csv(fl_restuarants2019)

df_fl2019

,Geographic Area Name (NAME),2017 NAICS code (NAICS2017),Meaning of NAICS code (NAICS2017_LABEL),Meaning of Legal form of organization code (LFO_LABEL),Meaning of Employment size of establishments code (EMPSZES_LABEL),Year (YEAR),Number of establishments (ESTAB),"Annual payroll ($1,000) (PAYANN)","First-quarter payroll ($1,000) (PAYQTR1)",Number of employees (EMP)
0,Florida,722511,Full-service restaurants,All establishments,All establishments,2019,"17,000","9,338,660","2,401,862","436,904"
1,Florida,722511,Full-service restaurants,All establishments,Establishments with less than 5 employees,2019,"4,454","316,062","35,435","7,048"
2,Florida,722511,Full-service restaurants,All establishments,Establishments with 5 to 9 employees,2019,"2,489","329,390","84,326","16,898"
3,Florida,722511,Full-service restaurants,All establishments,Establishments with 10 to 19 employees,2019,"2,945","810,238","212,425","41,448"
4,Florida,722511,Full-service restaurants,All establishments,Establishments with 20 to 49 employees,2019,"4,337","2,759,569","726,424","137,860"
5,Florida,722511,Full-service restaurants,All establishments,Establishments with 50 to 99 employees,2019,"2,148","3,094,582","817,701","144,722"
6,Florida,722511,Full-service restaurants,All establishments,Establishments with 100 to 249 employees,2019,600,"1,772,995","458,873","79,661"
7,Florida,722511,Full-service restaurants,All establishments,Establishments with 250 to 499 employees,2019,26,"227,137","58,471","8,649"
8,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,All establishments,2019,"3,807","3,019,508","767,037","143,067"
9,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with less than 5 employees,2019,926,"63,573","7,204","1,440"
10,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with 5 to 9 employees,2019,387,"48,167","11,890","2,519"
11,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with 10 to 19 employees,2019,412,"110,307","27,635","5,996"
12,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with 20 to 49 employees,2019,942,"612,242","157,072","31,969"
13,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with 50 to 99 employees,2019,839,"1,257,988","326,686","57,960"
14,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with 100 to 249 employees,2019,282,"765,129","195,805","36,826"
15,Florida,722511,Full-service restaurants,C-corporations and other corporate legal forms...,Establishments with 250 to 499 employees,2019,19,"162,102","40,745","6,357"
16,Florida,722511,Full-service restaurants,S-corporations,All establishments,2019,"8,675","3,870,134","1,006,533","180,755"
17,Florida,722511,Full-service restaurants,S-corporations,Establishments with less than 5 employees,2019,"2,155","135,821","20,611","3,983"
18,Florida,722511,Full-service restaurants,S-corporations,Establishments with 5 to 9 employees,2019,"1,509","208,897","54,118","10,346"
19,Florida,722511,Full-service restaurants,S-corporations,Establishments with 10 to 19 employees,2019,"1,846","516,400","135,816","25,810"
20,Florida,722511,Full-service restaurants,S-corporations,Establishments with 20 to 49 employees,2019,"2,288","1,458,348","385,800","70,462"
21,Florida,722511,Full-service restaurants,S-corporations,Establishments with 50 to 99 employees,2019,699,"981,070","261,363","45,461"
22,Florida,722511,Full-service restaurants,S-corporations,Establishments with 100 to 249 employees,2019,174,"529,945","137,249","23,385"
23,Florida,722511,Full-service restaurants,S-corporations,Establishments with 250 to 499 employees,2019,4,"39,653","11,576","1,308"
24,Florida,722511,Full-service restaurants,Individual proprietorships,All establishments,2019,"1,011","435,729","109,436","21,833"
25,Florida,722511,Full-service restaurants,Individual proprietorships,Establishments with less than 5 employees,2019,417,"19,193","2,270",599
26,Florida,722511,Full-service restaurants,Individual proprietorships,Establishments with 5 to 9 employees,2019,146,"17,253","4,325",979
27,Florida,722511,Full-service restaurants,Individual proprietorships,Establishments with 10 to 19 employees,2019,130,"31,047","7,955","1,800"
28,Florida,722511,Full-service restaurants,Individual proprietorships,Establishments with 20 to 49 employees,2019,143,"85,441","22,775","4,577"
29,Florida,722511,Full-service restaurants,Individual proprietorships,Establishments with 50 to 99 employees,2019,156,"199,640","50,557","10,805"
30,Florida,722511,Full-service restaurants,Individual proprietorships,Establishments with 100 to 249 employees,2019,18,"54,468","13,347","2,455"
31,Florida,722511,Full-service restaurants,Partnerships,All establishments,2019,"3,485","1,992,429","513,865","90,389"
32,Florida,722511,Full-service restaurants,Partnerships,Establishments with less than 5 employees,2019,949,"97,013","5,256","1,017"
33,Florida,722511,Full-service restaurants,Partnerships,Establishments with 5 to 9 employees,2019,446,"54,695","13,904","3,049"
34,Florida,722511,Full-service restaurants,Partnerships,Establishments with 10 to 19 employees,2019,555,"151,865","40,863","7,803"
35,Florida,722511,Full-service restaurants,Partnerships,Establishments with 20 to 49 employees,2019,960,"601,424","160,254","30,733"
36,Florida,722511,Full-service restaurants,Partnerships,Establishments with 50 to 99 employees,2019,447,"643,397","175,930","29,996"
37,Florida,722511,Full-service restaurants,Partnerships,Establishments with 100 to 249 employees,2019,125,"418,653","111,508","16,807"
38,Florida,722511,Full-service restaurants,Partnerships,Establishments with 250 to 499 employees,2019,3,"25,382","6,150",984
39,Florida,722511,Full-service restaurants,Non-profit,All establishments,2019,11,"2,857",732,163
40,Florida,722511,Full-service restaurants,Non-profit,Establishments with less than 5 employees,2019,5,435,94,9
41,Florida,722511,Full-service restaurants,Other noncorporate legal forms of organization,All establishments,2019,11,"18,003","4,259",697
42,Florida,722511,Full-service restaurants,Other noncorporate legal forms of organization,Establishments with 50 to 99 employees,2019,6,"11,812","2,969",452

In [13]:
df_2019_2021 = pd.concat([df_fl2019, df_fl2020, df_fl2021], ignore_index=True)

print(df_2019_2021)

    Geographic Area Name (NAME)  2017 NAICS code (NAICS2017)  \
0                       Florida                       722511
1                       Florida                       722511
2                       Florida                       722511
3                       Florida                       722511
4                       Florida                       722511
..                          ...                          ...
128                     Florida                       722511
129                     Florida                       722511
130                     Florida                       722511
131                     Florida                       722511
132                     Florida                       722511

    Meaning of NAICS code (NAICS2017_LABEL)  \
0                  Full-service restaurants
1                  Full-service restaurants
2                  Full-service restaurants
3                  Full-service restaurants
4                  Full-service restaurants
..                                      ...
128                                     NaN
129                                     NaN
130                                     NaN
131                                     NaN
132                                     NaN

    Meaning of Legal form of organization code (LFO_LABEL)  \
0                                   All establishments
1                                   All establishments
2                                   All establishments
3                                   All establishments
4                                   All establishments
..                                                 ...
128                                         Non-profit
129                                         Non-profit
130     Other noncorporate legal forms of organization
131     Other noncorporate legal forms of organization
132     Other noncorporate legal forms of organization

    Meaning of Employment size of establishments code (EMPSZES_LABEL)  \
0                                   All establishments
1            Establishments with less than 5 employees
2                 Establishments with 5 to 9 employees
3               Establishments with 10 to 19 employees
4               Establishments with 20 to 49 employees
..                                                 ...
128          Establishments with less than 5 employees
129             Establishments with 10 to 19 employees
130                                 All establishments
131               Establishments with 5 to 9 employees
132             Establishments with 20 to 49 employees

     Year (YEAR) Number of establishments (ESTAB)  \
0           2019                           17,000
1           2019                            4,454
2           2019                            2,489
3           2019                            2,945
4           2019                            4,337
..           ...                              ...
128         2021                                7
129         2021                                4
130         2021                               10
131         2021                                3
132         2021                                3

    Annual payroll ($1,000) (PAYANN) First-quarter payroll ($1,000) (PAYQTR1)  \
0                          9,338,660                                2,401,862
1                            316,062                                   35,435
2                            329,390                                   84,326
3                            810,238                                  212,425
4                          2,759,569                                  726,424
..                               ...                                      ...
128                            1,965                                       78
129                            1,022                                      207
130                            4,060                                    1,156
131                              470                                      184
132                            2,327                                      442

    Number of employees (EMP) Meaning of NAICS Code (NAICS2017_LABEL)
0                     436,904                                     NaN
1                       7,048                                     NaN
2                      16,898                                     NaN
3                      41,448                                     NaN
4                     137,860                                     NaN
..                        ...                                     ...
128                         9                Full-service restaurants
129                        55                Full-service restaurants
130                       188                Full-service restaurants
131                        22                Full-service restaurants
132                        74                Full-service restaurants

[133 rows x 11 columns]